sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip uninstall pytest -y
  - pip install coveralls
  - pip install -e .[test]
script:
  - py.test --cov=wagtailspeech --cov-report=xml
  - flake8 src/
after_success:
  - coveralls
